### ISSUE TITLE
Data index and video file not found for this day.

### ISSUE THREAD

**Issue by Jammer-hammer** [yuka-friends/Windrecorder#255]
Application worked before the 0.29 update.
Then stopped showing new recordings in the UI.
Windows 11

Troubleshooting i ended up deleting prefix_2024-12_wind.db, running the update again, uninstalling and reinstalling the entire application.

The application does take screenshots. It does combine them into videofiles, and it does seem to run OCR on the videofiles.
I cant at least see files in _\Windrecorder\userdata\videos\_ like _2024-12-05_15-12-12-SCREENSHOTS-OCRED.mp4_

However, in the WEB UI, under Daily for any given day, I get the following: _Data index and video file not found for this day._
Earliest record time: 2024/12/05 15:08:53, latest record time: 2024/12/05 15:08:53, index lines: 1, video storage: 0.003 GB (3 video files)
This is a relative low number now, because i just reset the entire application with userdata while troubleshooting.

Under Settings, it tells me there are no new videos that need indexing at the moment.
my prefix is correct set for my config_user.json but I do see under _\userdata\db_, that in addition to my prefix, there is a _default_2024-12_wind.db_

**Comment by Antonoko** [comment]
Thanks for the feedback! I have tested my environment here, and no matter which recording mode or whether it is a new installation, I have not been able to successfully reproduce the bug of not being able to record. :/

I guess that in some steps after the upgrade, the user name in the config file was reset or modified, causing the prefix to not match the original database file? You can try to check `"user_name"` in `userdata\config_user.json`. (I think I should optimize the upgrade process. Usually, when the upgrade is completed, it can be directly closed install_update.bat. There is no need to run the setup wizard again and again, which may cause the configuration to be overwritten.

Also, for further investigation, you can use a text editor such as vscode to view the updated log information in `cache\logs\wr.log` when windrecorder is running. Alternatively, you can create `DEBUGMODE.txt` in the windrecorder directory, and then manually execute the following command to observe the output of the process and the cache_screenshot directory (if using flexible screenshot mode

```
poetry shell
python record_screen.py
```

**Comment by Jammer-hammer** [comment]
The problem is actually not that its not recording for me. I can see both screenshots and video files in explorer. The web ui just does not show them on the Daily tab.

It does however inform me that there are video files recorded on the Daily tab with the message: 
_Earliest record time: 2024/12/06 13:34:43, latest record time: 2024/12/08 00:06:19, index lines: 17, video storage: 0.032 GB (25 video files)_

And on the Settings tab, I can see it has indexed some videofiles: _No new videos need indexing at the moment. (There are 30 files on disk._


**The prefix is the same in all my instances.** 
- "user_name" in `userdata\config_user.json`
- prefix for my videofiles and the prefix for my `userdata\db\`
- There is however a default prefix in this folder as well. I have deleted this, but it gets recreated automatically.



I did however observe a new thing. 
Last night I was using my laptop without external screens, and these videofiles are in the web ui.
My external screens are 2 monitors: 1 ultrawide, on 4k in portrait mode.

So to reiterate:
the tool does record screenshots, and converts them to videofiles, that gets indexed.
But the web UI does not show a scrubbing video on the daily tab i can search in, if I have external monitors attached.

**Comment by Antonoko** [comment]
> Can you add the option to revert to last upgrade of .28 instead?

Yes, you can roll back the version by executing the command in the directory

`git reset --soft 167f1a4` （I recommend rollback to 0e2dcf8, which resolved a serious deprecation bug

All the update records of the program can be found here. Some bugs were fixed after version .28. You can roll back to the corresponding position as needed (the bugs fixed and the new features added currently seem to be unrelated to the failure, and I am also confused): https://github.com/yuka-friends/Windrecorder/commits/main/

**Comment by Antonoko** [comment]
@Jammer-hammer Thank you for your detailed troubleshooting! The lack of multiple monitors in my test environment seems to be a blind spot. I will look for opportunities to test multiple monitors. If only the webui is not updated, I guess the database may not be written or updated correctly. You can observe the modification time and size of the files under `userdata\db` to see if they are updated. At the same time, you can delete the file with the suffix `_TEMP_READ` when the webui is closed, so that the latest database read copy will be created when the webui is restarted.

If a more detailed investigation is required, you can create `DEBUGMODE.txt` in the windrecorder directory, and then manually execute the following command to observe the output of webui running:

```
poetry shell
streamlit run webui.py
```

**Comment by Jammer-hammer** [comment]
I can add,
That I am working from a laptop, which I hook up to two different setups with vastly different monitor setups.
Station 1: 3 x 16:9 screens
Stations 2: 2 x 21:9 Screens

I can see the video files by manually looking in the folders, and they are all captured correctly.

I am also currently running 0.28, but it does not seem to resolve the issue. So my issue might be unrelated to the update itself, but maybe the update procedure on my PC.
I have uninstalled the software and tried to install it fresh.

As a test, I have set it to only record one screen currently, and awaiting to see if it produces any results.

**Comment by Jammer-hammer** [comment]
When unplugging my laptop from external monitors, the recorded video is shown in the web ui.
But when selecting to only record one of the external monitors, the recorded video is not shown in web UI.

All options are indeed recorded, but the web ui, will only show the video recorded, if i only recorded my laptop screen.

Today, after having the option set to only record one screen, I got the following error in the bottom of the ui

`StreamlitAPIException: Selectbox index must be greater than or equal to 0 and less than the length of options.

Traceback:
File "C:\GIT\Windrecorder\webui.py", line 115, in <module>
    main_webui()
File "C:\GIT\Windrecorder\webui.py", line 89, in main_webui
    windrecorder.ui.recording.render()
File "C:\GIT\Windrecorder\windrecorder\ui\recording.py", line 140, in render
    display_record_selection = st.selectbox(
                               ^^^^^^^^^^^^^
![Screenshot 2024-12-10 100341](https://github.com/user-attachments/assets/71635629-0f3a-44ce-9a35-61c9de13aee0)
`
